-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module HierMod.Abs where

newtype Name = Name String
  deriving (Eq, Ord, Show, Read)

data Program = Prg Name [Decl]
  deriving (Eq, Ord, Show, Read)

data Decl
    = Modl Name [Decl]
    | PrivateModl Name [Decl]
    | Open [Name]
    | OpenPublic [Name]
  deriving (Eq, Ord, Show, Read)

