# dist: trusty
sudo: required
language: r

# services:
#   - docker

before_install:
  # - sudo apt-get -q update
  # - sudo apt-get install -y texlive-latex-extra texlive-math-extra
  # - docker pull jlimperg/agda-stdlib
  # - docker pull adnrv/texlive:custom
  # texlive/texlive
  # 


script:
  - make docs

deploy:
  provider: pages
  local_dir: ./docs
  project_name: "Notes and Prototypes concerning Agda's Scope Checker"
  skip_cleanup: true
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
