-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module HierMod.Abs where

import qualified Data.Text

newtype Name = Name Data.Text.Text
  deriving (Eq, Ord, Show, Read)

data Program = Prg Name Decls
  deriving (Eq, Ord, Show, Read)

data Decl = Modl Name Decls | Ref QName
  deriving (Eq, Ord, Show, Read)

data Decls = DNil | DSnoc Decls Decl
  deriving (Eq, Ord, Show, Read)

data QName = QName Name | Qual Name QName
  deriving (Eq, Ord, Show, Read)

