-- File generated by the BNF Converter (bnfc 2.9.5).

-- Test for Agda binding of parser.  Requires Agda >= 2.5.4.

module HierMod.Main where

open import Agda.Builtin.Bool using (true)
open import HierMod.IOLib
open import HierMod.AST using (printProgram)
open import HierMod.Parser using (Err; parseProgram)

main : IO ⊤
main = do
  file ∷ [] ← getArgs where
    _ → do
      putStrLn "usage: Main <SourceFile>"
      exitFailure
  Err.ok result ← parseProgram true <$> readFiniteFile file where
    Err.bad msg → do
      putStrLn "PARSE FAILED\n"
      putStrLn (stringFromList msg)
      exitFailure
  putStrLn "PARSE SUCCESSFUL\n"
  putStrLn (printProgram result)
